风云足球:
  name:
    - 风云足球
  scraper:
    tvmao: CCTVPAYFEE-CCTVPAYFEE13
    cctv: 
  refresh: once
  recap: 7
  preview: 2

高尔夫网球:
  name:
    - 高尔夫网球
  scraper:
    tvmao: cctvpsyfee13
    cctv: 
  refresh: once
  recap: 7
  preview: 2
